name: ldc2
version: "1.0.0"
summary: D compiler with LLVM backend
description: LDC is a compiler for the D programming Language.
             It is based on the latest DMD frontend and uses LLVM for code
             generation.
license: LICENSE
confinement: strict

apps:
  ldc2:
    command: ldc2
    plugs: [home]
  ldmd2:
    command: ldmd2
    plugs: [home]

parts:
  ldc:
    source: git://github.com/ldc-developers/ldc.git
    source-tag: v1.0.0
    plugin: cmake
    snap:
    - '*'
    - -etc/ldc2.conf
    build-packages:
    - build-essential
    - ldc
    - llvm-dev
    - libconfig++-dev
    - libcurl4-gnutls-dev
    - libedit-dev
    - zlib1g-dev
  ldc-config:
    plugin: dump
    source: ldc-config
    organize:
      ldc2.conf: etc/ldc2.conf

  gcc:
    plugin: nil
    stage-packages: [gcc]
    organize:
      usr/bin/gcc: usr/bin/gcc.real
  gcc-wrapper:
    plugin: dump
    source: gcc-wrapper
    organize:
      gcc.wrapper: usr/bin/gcc
  libc6:
    plugin: nil
    stage-packages: [libc6]
  libc6-dev:
    plugin: nil
    stage-packages: [libc6-dev]
